#!/bin/bash

# Slowly decreases the volume.

echo
echo "Sleep Volume"
echo "It is $(date)"
export XDG_RUNTIME_DIR=/run/user/1000

echo
echo "Stat"
pactl stat

echo
echo "Info"
pactl info

# Get directory of this script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
echo
echo "Running from $DIR"


# Set initial volume
echo
echo "Setting volume"
pactl set-sink-volume 1 80%


# Decrease volume gradually
echo
for run in {1..100}
do
    echo "Decreasing volume"
    sleep 77
    pactl set-sink-volume 1 -1%
done


# Normal termination
echo
echo "You should be sleeping now!!"
